const router = require('express').Router()
const { register, login, authTest, followUser, logout, updatePassword, updateProfile, deleteMyProfile, getMyProfile, getUserProfile, getAllUsers, forgotPassword, resetPassword, getMyPosts, getUserPosts } = require('../controllers/User')
const { isAuthenticated } = require('../middleware/auth')

router.post('/register',register)
router.post('/login',login)
router.get('/logout',isAuthenticated,logout)
router.get('/test',isAuthenticated)
router.get('/follow/:id',isAuthenticated,followUser)
router.put('/update/password',isAuthenticated,updatePassword)
router.put('/update/profile',isAuthenticated,updateProfile)
router.delete('/delete',isAuthenticated,deleteMyProfile)
router.get('/me',isAuthenticated,getMyProfile)
router.get('/user/:id',isAuthenticated,getUserProfile)
router.get('/users',isAuthenticated,getAllUsers)
router.post('/forgot/password',forgotPassword)
router.put('/password/reset/:token',resetPassword)
router.get('/my/posts',isAuthenticated,getMyPosts)
router.get('/userposts/:id',isAuthenticated,getUserPosts)
module.exports = router